# coding: utf-8

"""
    Artifact API

    API for managing Graph RAGs  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GraphQuery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'namespace': 'str',
        'prompt': 'str'
    }

    attribute_map = {
        'namespace': 'namespace',
        'prompt': 'prompt'
    }

    def __init__(self, namespace=None, prompt=None):  # noqa: E501
        """GraphQuery - a model defined in Swagger"""  # noqa: E501
        self._namespace = None
        self._prompt = None
        self.discriminator = None
        if namespace is not None:
            self.namespace = namespace
        if prompt is not None:
            self.prompt = prompt

    @property
    def namespace(self):
        """Gets the namespace of this GraphQuery.  # noqa: E501


        :return: The namespace of this GraphQuery.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this GraphQuery.


        :param namespace: The namespace of this GraphQuery.  # noqa: E501
        :type: str
        """

        self._namespace = namespace

    @property
    def prompt(self):
        """Gets the prompt of this GraphQuery.  # noqa: E501


        :return: The prompt of this GraphQuery.  # noqa: E501
        :rtype: str
        """
        return self._prompt

    @prompt.setter
    def prompt(self, prompt):
        """Sets the prompt of this GraphQuery.


        :param prompt: The prompt of this GraphQuery.  # noqa: E501
        :type: str
        """

        self._prompt = prompt

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GraphQuery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GraphQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
